import {
  bull,
  burning,
  guernica,
  eiffel,
  starry,
  gertrude,
  gargantua,
  madwoman,
  galette,
  medusa,
  salisbury,
  apples,
  stone,
  sunday,
  sainte,
  boating,
  dream,
  gleaners,
  clinic,
  scream,
  moon,
  scythe,
  hat,
} from "../images";

const paintings = [
  {
    image: bull,
    title: "The Bull",
    painter: "Pablo Picasso",
    year: "1943",
    medium: "Assemblage of bicycle saddle and handlebars",
  },
  {
    image: burning,
    title: "The Burning of the Houses of Lords and Commons",
    painter: "Jospeh William Mallord Turner",
    year: "1834-35",
    medium: "Oil on fabric",
  },
  {
    image: guernica,
    title: "Guernica",
    painter: "Pablo Picasso",
    year: "1937",
    medium: "Oil on canvas",
  },
  {
    image: eiffel,
    title: "The Eiffel Tower",
    painter: "Alexandre Gustave Eiffel",
    year: "1887-89",
    medium: "Wrought iron superstructure with reinforced concrete",
  },
  {
    image: madwoman,
    title: "Madwoman with a Mania of Envy",
    painter: "Theodore Gericault",
    year: "1822-23",
    medium: "Oil on canvas",
  },
  {
    image: starry,
    title: "The Starry Night",
    painter: "Vincent van Gogh",
    year: "1889",
    medium: "Oil on canvas",
  },
  {
    image: gertrude,
    title: "Gertrude Stein",
    painter: "Pablo Picasso",
    year: "1906",
    medium: "Oil on canvas",
  },
  {
    image: gargantua,
    title: "Louis Philippe as Gargantua",
    painter: "Honore Daumier",
    year: "1831",
    medium: "Lithograph",
  },
  {
    image: galette,
    title: "Moulin de la Galette",
    painter: "Pierre Auguste Renoir",
    year: "1876",
    medium: "Oil on canvas",
  },
  {
    image: medusa,
    title: "Raft of the Medusa",
    painter: "Theodore Gericault",
    year: "1819",
    medium: "Oil on canvas",
  },
  {
    image: salisbury,
    title: "Salisbury Cathedral from the Bishop's Garden",
    painter: "John Constable",
    year: "1820",
    medium: "Oil on canvas",
  },
  {
    image: apples,
    title: "Still Life with Apples",
    painter: "Paul Cezanne",
    year: "1875-77",
    medium: "Oil on canvas",
  },
  {
    image: stone,
    title: "The Stone Breakers",
    painter: "Gustave Courbet",
    year: "1849",
    medium: "Oil on canvas",
  },
  {
    image: sunday,
    title: "Sunday Afternoon on the Island of La Grande Jatte",
    painter: "Georges Seurat",
    year: "1884-86",
    medium: "Oil on canvas",
  },
  {
    image: sainte,
    title: "Terrace at Sainte-Adresse",
    painter: "Claude Monet",
    year: "1866-67",
    medium: "Oil on canvas",
  },
  {
    image: boating,
    title: "The Boating Party",
    painter: "Mary Cassatt",
    year: "1893-94",
    medium: "Oil on canvas",
  },
  {
    image: dream,
    title: "The Dream",
    painter: "Henry Rousseau",
    year: "1910",
    medium: "Oil on canvas",
  },
  {
    image: gleaners,
    title: "The Gleaners",
    painter: "Jean Francois Millet",
    year: "1857",
    medium: "Oil on canvas",
  },
  {
    image: clinic,
    title: "The Gross Clinic",
    painter: "Thomas Cowperthwait Eakins",
    year: "1875-76",
    medium: "Oil on canvas",
  },
  {
    image: scream,
    title: "The Scream",
    painter: "Edvard Munch",
    year: "1893",
    medium: "Oil, pastel and casein on cardboard",
  },
  {
    image: moon,
    title: "Two men contemplating the moon",
    painter: "Caspar David Friedrich",
    year: "1819",
    medium: "Oil on canvas",
  },
  {
    image: scythe,
    title: "Whetting the Scythe",
    painter: "Kathe Kollwitz",
    year: "1904",
    medium: "soft ground 8th state etching",
  },
  {
    image: hat,
    title: "woman with the hat",
    painter: "Henri Matisse",
    year: "1905",
    medium: "Oil on canvas",
  },
  // Add more paintings here
];

export default paintings;
